---
- name: Clone the dumbo-octopus/ansible repo
  hosts: all
  # connection: local
  gather_facts: no
    
    - name: Ensure PIP is installed
      shell: python -m ensurepip

    - name: Upgrade pip
      shell: python -m pip install -U pip

    - name: Install Ansible via pip
      pip:
        name: ansible
        state: present
    
    - name: Clone ansible and flow repos
      git:
        repo: "{{ item }}"
        dest: /dumbo-octopus
        clone: true
        update: true
      with_items:
        - https://github.com/dumbo-octopus/flow
        - https://github.com/dumbo-octopus/ansible