Vagrant.configure("2") do |config|
  config.vm.box = ENV['vmOS']
  config.vm.hostname = ENV['nodeName'] #`export nodeName=<your_node_name>` in bash
  config.vm.provider ENV['provider'] do |v| #libvirt -> virtualbox
    v.cpus=3
    v.memory=4096
  end
end
